camera0: "13051150"
camera1: "13051250"
frame_width: 1280
frame_height: 720
mono_calibration_frames: 10
stereo_calibration_frames: 10
view_resize: 2
checkerboard_box_size_scale : 4
checkerboard_rows: 4
checkerboard_columns: 6
cooldown: 75
